### ISSUE TITLE
Save/Restore removes tableDock from demo

### ISSUE THREAD

**Issue by jplwill** [ClearControl/DockFX#18]
Using the File/Save then File/Restore menu items in the DockFX demo app makes the "tableDock" DockNode vanish.  I've seen this happen two different ways.

1. If I start DockFX and immediately File/Save then File/Restore, it simply vanishes as though it had been closed.
2. In another case, where I'd moved things around a bit more, it vanished leaving a hole.  Its parent SplitPane created with an empty space where it should have been.

**Comment by hkmoon** [comment]
Could you try it with the latest update?

**Comment by jplwill** [comment]
I'm still seeing it on the master branch.  Is there another branch I should be looking at?

**Comment by hkmoon** [comment]
Sorry for the late reply. 
Actually, save/restore are working on the docks with proper titles in order to identify the window. Please, set up the titles for all the docking windows. ;)
