### ISSUE TITLE
Weird ComboBox Display in Tabbed DockNode

### ISSUE THREAD

**Issue by jplwill** [ClearControl/DockFX#21]
If I include a ComboBox in a GridPane in a DockNode, and add the DockNode to a DockPane so that it gets displayed as a Tab, sometimes I see an extra "down arrow" icon at the upper left of the ComboBox.  This doesn't happen in simpler cases.  (See the attached picture.)

Here's the program that produced it:

```
public class Dockfxbug extends Application {
    
    @Override
    public void start(Stage primaryStage) {
        DockPane dockPane = new DockPane();
        DockNode lastNode = null;

        for (int i = 1; i <= 2; i++) {
            GridPane grid = new GridPane();
            grid.setPadding(new Insets(10,10,10,10));
            Label label = new Label("A ComboBox:"); 
            ComboBox<String> combo = new ComboBox();
            combo.setValue("Combo" + i);
            combo.setEditable(false);

            GridPane.setConstraints(label, 0, 0);
            GridPane.setConstraints(combo, 1, 0);
            grid.getChildren().addAll(label, combo);

            DockNode node = new DockNode(grid,"Combo" + i);
            node.setPrefSize(300, 300);

            if (lastNode == null) {
                node.dock(dockPane, DockPos.TOP);
            } else {
                node.dock(dockPane, DockPos.CENTER, lastNode);
            }
            lastNode = node;
        }
        
        StackPane root = new StackPane();
        root.getChildren().add(dockPane);
        
        Scene scene = new Scene(root, 400, 400);
        
        primaryStage.setTitle("Hello World!");
        primaryStage.setScene(scene);
        primaryStage.show();

        Application.setUserAgentStylesheet(Application.STYLESHEET_MODENA);
        DockPane.initializeDefaultUserAgentStylesheet();
    }
```

I'm using SamCooper's latest version of DockFX, as of 11/15/2006.

![dockfxcomboboxbug](https://cloud.githubusercontent.com/assets/15933237/20320436/ae83a9f6-ab26-11e6-85cc-d92b3a09c4ee.png)

**Comment by jplwill** [comment]
I found something else that's interesting.  I added some items to the combo boxes, and added an onAction handler to print something when it fires:

```
ComboBox<String> combo = 
                new ComboBox(FXCollections.observableArrayList(
                    "Option 1",
                    "Option 2",
                    "Option 3"
                ));
            combo.setValue("Combo" + i);
            combo.setEditable(false);
            combo.setOnAction(evt -> {
                System.out.println("onAction(" + combo.getValue() + ")");
            });
```

When I run this program, if I select a new item from Combo2 the onAction event fires *twice*.

I found behavior in a real program; and if I add the relevant component to my GUI outside the DockPane it doesn't happen.  Looks like some of the DockPane's event handling is confusing widgets in DockNodes.

**Comment by MilWolf** [comment]
If you comment the line 

> this.setStyle("-fx-skin: \"org.dockfx.pane.skin.ContentTabPaneSkin\";");

from the file "ContentTabPane.java" the problem disappear.
So maybe the developper who wrote the class "ContentTabPaneSkin" can look into it.
