### ISSUE TITLE
Question: How do I attach an event to closing a DockNodeI

### ISSUE THREAD

**Issue by madhephaestus** [ClearControl/DockFX#3]
I need to be aware of a DockNode closing, is there a way to attach some event listener to do this? 

The equivalent in a Tab would be Tab.setOnCloseRequest(event -> {})

**Comment by hkmoon** [comment]
```DockNode``` has closedProperty() where you can add ```ChangeListener<Boolean>()```.
This event handler will be called when the docking window is closed.
This is different from closableProperty() which is used for making close button in the title bar.

**Comment by madhephaestus** [comment]
Oh thank you! For us newbs, it would be super helpful if things like this were in the DockerFX.java demo application.

**Comment by hkmoon** [comment]
No problem. Thanks to your comment, a ```closedProperty()``` usecase is added in 1580438543c34f81f6ccc5aa770a90b24f772689.
