### ISSUE TITLE
DockFX.java demo application does not work with tabbing

### ISSUE THREAD

**Issue by madhephaestus** [ClearControl/DockFX#4]
the section where this is called:
    // let's disable our table from being undocked
    tableDock.setDockTitleBar(null);
Causes nullpointerexception if that element if used as a center-dragged tab. 

To replicate the error set tableDock to dock at center, and then  have tabs doce to the tableDock:
tableDock.dock(dockPane, DockPos.CENTER);
 tabsDock.dock(dockPane, DockPos.CENTER,tableDock);//exception is thrown from here

Commenting out the line where the DockTitleBar is set to null works around this issue.

**Comment by hkmoon** [comment]
Thank you for reporting it.
Actually, making DockPos.CENTER without siblings (which means some other dockNode should be provided for making multi tabs) is not possible. Personally, I would propose the below codes:

```java
    DockNode tabsDock = new DockNode(tabs, "Tabs Dock", new ImageView(dockImage));
    tabsDock.setPrefSize(300, 100);
    tabsDock.dock(dockPane, DockPos.TOP);
    DockNode tableDock = new DockNode(tableView, "Table Dock", new ImageView(dockImage));
    tableDock.setPrefSize(300, 100);
    tableDock.dock(dockPane, DockPos.CENTER, tabsDock);
```

Just replace the old codes with the new ones.
