### ISSUE TITLE
TabHeaderSkin uses missing library com/sun/javafx/util/Utils

### ISSUE THREAD

**Issue by madhephaestus** [ClearControl/DockFX#5]
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/util/Utils
    at org.dockfx.pane.skin.ContentTabPaneSkin$TabHeaderSkin$4.layoutChildren(ContentTabPaneSkin.java:1252)

com/sun/javafx/util/Utils has been removed from the JVM as of Java 8 build 40. Only Mac seems strict about this causing docking not to work on Mac with the latest JVM. The same code works on Linux.

**Comment by madhephaestus** [comment]
The problem is that the class com.sun.javafx.Utils was moved to com.sun.javafx.util.Utils package in update 60 of Java 8. I am running Java 8 build 91.

**Comment by madhephaestus** [comment]
Bug can be worked around by creating a class com.sun.javafx.util.Utils that extends com.sun.javafx.Utils and this issue can be bypassed.

**Comment by hkmoon** [comment]
In order to avoid this issue, please, use the JDK above the version 8u60. Thank you for the tip. ;)
