### ISSUE TITLE
Top most DockHandle doesnt seem to work

### ISSUE THREAD

**Issue by jasons2000** [ClearControl/DockFX#6]
When trying to Dock a Window the topmost Dock Handle doesn't seem to work, it disappears before you get the chance to dock onto it.

**Comment by jasons2000** [comment]
Ok,  the top and bottom dock handles are not correctly placed. My application has a toolbar and I don't think it corerectly accounts for his

**Comment by jasons2000** [comment]
this is fixed on https://github.com/SamCooper/DockFX/commit/bdb11594098813561cb14a295ac406871dbbde03

**Comment by hkmoon** [comment]
I close this issue thanks to your brilliant #11.
