### ISSUE TITLE
FXML support

### ISSUE THREAD

**Issue by dhakehurst** [ClearControl/DockFX#9]
I'm looking for FXML support for DockFX.

Started discussing with @SamCooper, he suggested moving the discussion to here
[https://github.com/RobertBColton/DockFX/issues/21]

I started trying to provide support, but don't really know how to do it.
(see [https://github.com/RobertBColton/DockFX/issues/21])

Any help gratefully received.

ref
@SamCooper
@hkmoon

**Comment by SamCooper** [comment]
She?! ;)

**Comment by dhakehurst** [comment]
sorry

**Comment by hkmoon** [comment]
Hi @dhakehurst,
I managed to merge the @SamCooper's great PR.
Hopefully, you like it!
